
#pragma once

// GENERATE BY RPCGEN. DO NOT EDIT THIS FILE.
// 此头文件包含当前名字空间下的所有协议。要注意，如果把实现写在头文件里面，
// 包含这个头文件很容易产生循环。

#include "fire/pb/battle/CEndWatchBattle.hpp"
#include "fire/pb/battle/CReqRePlay.hpp"
#include "fire/pb/battle/CSendAction.hpp"
#include "fire/pb/battle/CSendRoundPlayEnd.hpp"
#include "fire/pb/battle/CStopRePlay.hpp"
#include "fire/pb/battle/SRemoveWatcher.hpp"
#include "fire/pb/battle/SReqRePlay.hpp"
#include "fire/pb/battle/SSendAddFighters.hpp"
#include "fire/pb/battle/SSendBattleEnd.hpp"
#include "fire/pb/battle/SSendBattleStart.hpp"
#include "fire/pb/battle/SSendCameraUrl.hpp"
#include "fire/pb/battle/SSendRoundScript.hpp"
#include "fire/pb/battle/SSendRoundStart.hpp"
