
#pragma once

// GENERATE BY RPCGEN. DO NOT EDIT THIS FILE.
// 这个包含所有的协议
// 当把实现写在头文件中时，很容易产生循环。这时，不要使用这个文件。

#include "gnet/AddictionControl.hpp"
#include "gnet/AnnounceForbidInfo.hpp"
#include "gnet/Challenge.hpp"
#include "gnet/CouponExchangeRep.hpp"
#include "gnet/CouponExchangeReq.hpp"
#include "gnet/ErrorInfo.hpp"
#include "gnet/GetUserCouponRep.hpp"
#include "gnet/GetUserCouponReq.hpp"
#include "gnet/InstantAddCashRep.hpp"
#include "gnet/InstantAddCashReq.hpp"
#include "gnet/KeepAlive.hpp"
#include "gnet/KeyExchange.hpp"
#include "gnet/MatrixChallenge.hpp"
#include "gnet/MatrixResponse.hpp"
#include "gnet/OnlineAnnounce.hpp"
#include "gnet/PortForward.hpp"
#include "gnet/Response.hpp"
#include "infoserver/CGetServerInfo.hpp"
#include "infoserver/SGetServerInfo.hpp"
