/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mkdb_Storage_IWalk */

#ifndef _Included_xdb_Storage_IWalk
#define _Included_xdb_Storage_IWalk
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
