/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xio_security_Security */

#ifndef _Included_xio_security_Security
#define _Included_xio_security_Security
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xio_security_Security
 * Method:    open_compress
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_xio_security_Security_open_1compress
  (JNIEnv *, jobject);

/*
 * Class:     xio_security_Security
 * Method:    compress_update
 * Signature: (J[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_xio_security_Security_compress_1update
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     xio_security_Security
 * Method:    compress_final
 * Signature: (J[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_xio_security_Security_compress_1final
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     xio_security_Security
 * Method:    close_compress
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_xio_security_Security_close_1compress
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xio_security_Security
 * Method:    open_decompress
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_xio_security_Security_open_1decompress
  (JNIEnv *, jobject);

/*
 * Class:     xio_security_Security
 * Method:    decompress_update
 * Signature: (J[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_xio_security_Security_decompress_1update
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     xio_security_Security
 * Method:    close_decompress
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_xio_security_Security_close_1decompress
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xio_security_Security
 * Method:    open_security
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_xio_security_Security_open_1security
  (JNIEnv *, jobject, jint);

/*
 * Class:     xio_security_Security
 * Method:    security_set_parameter
 * Signature: (J[BI)V
 */
JNIEXPORT void JNICALL Java_xio_security_Security_security_1set_1parameter
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     xio_security_Security
 * Method:    security_update
 * Signature: (J[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_xio_security_Security_security_1update
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     xio_security_Security
 * Method:    security_final
 * Signature: (J[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_xio_security_Security_security_1final
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     xio_security_Security
 * Method:    colse_security
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_xio_security_Security_close_1security
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
