
#pragma once

// GENERATE BY RPCGEN. DO NOT EDIT THIS FILE.

#include <set>
#include <map>
#include <list>
#include <vector>

#include "win32/share.hpp"

// provider id
enum {
	FIRE_PB_PVID = 12,
};

namespace ProtoDef { 
void RegisterProtocols();
void UnregisterProtocols();
} 
